import type { Metadata } from 'next';
import { LufgaFont } from '@/lib/fonts';
import '../../app/globals.css';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={LufgaFont.className}>
        <h1>Doctor Dashboard Page</h1>
        {children}
      </body>
    </html>
  );
}
