import type { Metadata } from 'next';
import { LufgaFont } from '@/lib/fonts';
import '../../app/globals.css';
import DashboardLayout from '@/components/layouts/DashboardLayout';
import { ChakraClientProvider } from '@/providers/ChakraClientProvider';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={LufgaFont.className}>
        <ChakraClientProvider>
          <DashboardLayout>{children}</DashboardLayout>
        </ChakraClientProvider>
      </body>
    </html>
  );
}
