import type { Metadata } from 'next';
import { LufgaFont } from '@/lib/fonts';
import '../../app/globals.css';
import DashboardLayout from '@/components/layouts/DashboardLayout';
import { ChakraClientProvider } from '@/providers/ChakraClientProvider';
import { headers } from 'next/headers';
import AuthProvider from '@/components/shared/AuthProvider';
import NextTopLoader from 'nextjs-toploader';
import { DoctorDocProvider } from '@/lib/hooks/useDoctorDoc';

export const metadata: Metadata = {
  title: 'DOKTO',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  const userId = headers().get('x-user');

  return (
    <html lang="en">
      <body className={LufgaFont.className}>
        <NextTopLoader />
        <ChakraClientProvider>
          <AuthProvider uid={userId || ''}>
            {/* <LoggedInUserProvider value={JSON.stringify(userId)}> */}
            <DoctorDocProvider>
              <DashboardLayout>{children}</DashboardLayout>
            </DoctorDocProvider>
            {/* </LoggedInUserProvider> */}
          </AuthProvider>
        </ChakraClientProvider>
      </body>
    </html>
  );
}
