const conditions = {
  "gynecologist": [
    "amenorrhoea",
    "aplastic anemia",
    "ectopic pregnancy",
    "endometriosis",
    "female infertility",
    "female urinary problems",
    "fibroids",
    "gynaecological tumors",
    "high risk pregnancy",
    "infectious diseases",
    "menopause",
    "menstruation problems",
    "miscarriage",
    "ovarian cyst",
    "polycystic ovary syndrome (pcos)",
    "post menopausal bleeding",
    "preeclampsia",
    "pregnancy",
    "urinary tract infections (uti)",
    "uro gynae cancer"
  ],
  "dentist": [
    "canine teeth",
    "cavities",
    "dental caries",
    "dupuytren's contracture (hypodontia)",
    "gingivitis",
    "gum disease (periodontal)",
    "jaw joint problems",
    "orofacial pain",
    "periodontitis",
    "tmj disorders",
    "tooth decay",
    "toothache",
    "emotional outbursts"
  ],
  "obstetrician": [
    "infectious diseases",
    "amenorrhoea",
    "endometriosis",
    "female infertility",
    "female urinary problems",
    "gynaecological tumors",
    "high risk pregnancy",
    "menstruation problems",
    "miscarriage",
    "ovarian cyst",
    "post menopausal bleeding",
    "pregnancy",
    "urinary tract infections (uti)",
    "menopause",
    "aplastic anemia",
    "ectopic pregnancy",
    "fibroids",
    "polycystic ovary syndrome (pcos)",
    "preeclampsia",
    "uro gynae cancer"
  ],
  "general physician": [
    "abdomen pain",
    "abscess",
    "anemia",
    "arthritis",
    "bruise",
    "cardiac diseases",
    "chest infections",
    "chicken pox",
    "cold and influenza",
    "common cold",
    "constipation",
    "cough",
    "diarrhea",
    "fatigue",
    "fever",
    "flu",
    "general urology",
    "hypertension",
    "infectious diseases",
    "muscle aches",
    "nausea",
    "respiratory diseases",
    "sinusitis",
    "sleep disorders",
    "stomach pain",
    "urine problems",
    "vomiting",
    "acid peptic disease",
    "flatulence",
    "fissures",
    "gastric ulcer",
    "gastroenteritis",
    "hepatitis b",
    "hepatitis c",
    "jaundice",
    "liver diseases",
    "typhoid fever",
    "sports injury",
    "arthritis management",
    "bone fracture",
    "bone trauma",
    "childhood joints deformity",
    "fracture",
    "knee pain",
    "lower back pain",
    "musculoskeletal infection",
    "oesteoprosis",
    "road traffic accident",
    "trauma pain",
    "dengue",
    "addison's disease",
    "cancers of the endocrine gland",
    "cushing's syndrome",
    "diabetes insipidus",
    "goiter",
    "hyperthyroidism",
    "hypoglycemia",
    "hypothyroidism",
    "infertility",
    "lack of growth",
    "over or under production of hormones",
    "thyroid disease",
    "turner syndrome",
    "hemophilias",
    "hodgkin's lymphoma",
    "idiopathic thrombocytopenic purpura (itp)",
    "leukemia",
    "lymphoma",
    "platelets disorder",
    "thalassemia",
    "toxoplasmosis",
    "ttp",
    "abdominal pain",
    "black stools",
    "chronic hepatitis",
    "dyspepsia",
    "enteric fever",
    "helicobacter pylori bacteria",
    "hemorrhoids",
    "metabolic syndrome",
    "pancreas disease",
    "whooping cough",
    "diahrrea"
  ],
  "general surgeon": [
    "anal and perianal conditions",
    "anal fissure",
    "burns",
    "cyst",
    "diabetic foot",
    "fissure",
    "head injury",
    "lumps and bumps",
    "piles",
    "pilonidal cysts",
    "pilonidal sinus",
    "thoracic outlet syndrome",
    "varicose veins",
    "abscess",
    "anemia",
    "arthritis",
    "hypertension",
    "stroke",
    "abdominal aortic aneurysm (aaa)",
    "aortic arch conditions",
    "aortoiliac occlusive disease",
    "arm artery disease",
    "carotid artery disease",
    "chronic ulcers of the leg/foot",
    "chronic venous insufficiency",
    "chronic venous thrombosis",
    "deep vein thrombosis (dvt)",
    "diabetic vascular disease",
    "digital artery conditions",
    "hyperlipidemia",
    "leg artery disease",
    "lymphedema",
    "pelvic venous incompetence",
    "peripheral artery disease (pad)",
    "portal hypertension",
    "pulmonary embolism",
    "renovascular conditions",
    "thoracic aneurysm",
    "varicose and spider veins",
    "vascular malformations",
    "venous ulcerations",
    "visceral artery conditions",
    "renal failure"
  ],
  "pediatrician": [
    "abdomen diseases in children",
    "albinism",
    "allergy in children",
    "asthma in children",
    "birth defects",
    "cerebral palsy (cp)",
    "chest disease in children",
    "chest infection in children",
    "chicken pox",
    "childhood cancer",
    "childhood joints deformity",
    "down syndrome",
    "eating problems in children",
    "fever in children",
    "growth problem in children",
    "hypothyrodism",
    "kawasakis disease",
    "kidney problems in children",
    "measles",
    "meningitis",
    "mumps",
    "pneumonia in children",
    "respiratory disease in children",
    "respiratory tract infection (rti)",
    "rubella",
    "scarlet fever",
    "sturge weber syndrome",
    "teething issue",
    "tonsillitis",
    "tuberous sclerosis",
    "whooping cough",
    "hepatitis b",
    "hepatitis c",
    "liver diseases",
    "bile duct stones",
    "cholestasis",
    "cirrhosis",
    "hepatitis a",
    "hepatobiliary disease",
    "cleft lip and palate",
    "pediatric hernia",
    "undescended testicles",
    "hemophilias",
    "idiopathic thrombocytopenic purpura (itp)",
    "leukemia",
    "platelets disorder",
    "thalassemia",
    "hodgkin's lymphoma",
    "lymphoma"
  ],
  "family physician": [
    "constipation"
  ],
  "internal medicine specialist": [
    "hypertension",
    "cold and influenza",
    "anemia",
    "chest infections",
    "chicken pox",
    "common cold",
    "cough",
    "fatigue",
    "fever",
    "infectious diseases",
    "muscle aches",
    "sleep disorders",
    "abdominal pain",
    "acid peptic disease",
    "black stools",
    "chronic hepatitis",
    "dyspepsia",
    "enteric fever",
    "gastric ulcer",
    "gastroenteritis",
    "helicobacter pylori bacteria",
    "hepatitis b",
    "hepatitis c",
    "jaundice",
    "liver diseases",
    "metabolic syndrome",
    "pancreas disease",
    "typhoid fever",
    "abdomen pain",
    "arthritis",
    "cardiac diseases",
    "respiratory diseases",
    "angina",
    "arrythmias",
    "atherosclerosis",
    "atrial fibrillation",
    "cardiology diseases",
    "cardiovascular diseases",
    "congenital diseases",
    "heart attack",
    "heart diseases",
    "heart failure",
    "ischemic heart disease",
    "myocardial infarction (mi)",
    "palpitations",
    "pulmonary edema",
    "tachycardia",
    "addison's disease",
    "cholesterol disorders",
    "diabetes insipidus",
    "hyperthyroidism",
    "hypoglycemia",
    "hypothyroidism",
    "infertility",
    "lack of growth",
    "metabolic disorder",
    "over or under production of hormones",
    "thyroid disease",
    "cancers of the endocrine gland",
    "cushing's syndrome",
    "goiter",
    "turner syndrome",
    "bronchiectasis",
    "pulmonary hypertension",
    "tuberculosis",
    "atelectasis",
    "bronchial asthma",
    "chronic bronchitis",
    "chronic obstructive pulmonary diseases (copd)",
    "embolism",
    "emphysema",
    "interstitial lung disease (ild)",
    "sarcoidosis",
    "flatulence",
    "fissures",
    "hemorrhoids",
    "hernia",
    "nausea",
    "urinary stones",
    "kidney stone",
    "ureter stones",
    "urinary bladder stone",
    "aids",
    "allergic rhinitis",
    "amyloidosis",
    "bronchitis",
    "chest diseases",
    "chest infection",
    "coma",
    "copd",
    "coughing",
    "cystic fibrosis",
    "dermatomyositis",
    "duchenne muscular dystrophy",
    "electrolyte imbalances",
    "emphysena",
    "endocrine disorders",
    "hepatitis",
    "hiv",
    "infectious disease",
    "interstitial lung disease",
    "lung cancer",
    "metabolic acidosis",
    "progressive multifocal leukoencephalopathy (pml)",
    "purpura",
    "restless leg syndrome",
    "sjogren's syndrome",
    "tb chest",
    "tetanus",
    "flu",
    "dengue",
    "constipation",
    "sinusitis",
    "obesity",
    "tonsillitis",
    "hepatitis a",
    "hypothyrodism",
    "acute respiratory distress syndrome",
    "hypoxia",
    "mucus plug",
    "urine problems",
    "vomiting",
    "male infertility",
    "female infertility",
    "sports injury",
    "abscess",
    "general urology",
    "arthritis management",
    "bone fracture",
    "fracture",
    "lower back pain",
    "musculoskeletal infection",
    "road traffic accident",
    "knee pain",
    "oesteoprosis",
    "bruise",
    "hemophilias",
    "idiopathic thrombocytopenic purpura (itp)",
    "fibromyalgia",
    "ankylosing spondylitis",
    "bursitis / tendinitis",
    "giant cell arteritis",
    "gout",
    "hypersensitivity vasculitis",
    "mixed connective tissue disease",
    "myositis",
    "osteoarthritis",
    "polymyalgia rheumatica",
    "polymyositis / dermatomyositis",
    "psoriatic arthritis",
    "raynaud's phenomenon",
    "reactive arthritis",
    "rheumatoid arthritis",
    "scleroderma",
    "lung lymphoma",
    "tuberous sclerosis",
    "whooping cough",
    "high blood pressure",
    "asthma",
    "cardiac arrest",
    "bloating",
    "back ache",
    "blood pressure",
    "behcet's disease",
    "churg-strauss dyndrome",
    "corticosteroid-induced osteoporosis",
    "henoch-schonlein purpura",
    "osteoporosis",
    "juvenile rheumatoid arthritis",
    "kawasaki syndrome",
    "lupus",
    "polyarteritis nodosa",
    "primary antiphospholipid syndrome",
    "takayasu's arteritis",
    "undifferentiated spondyloarthropathy",
    "vasculitis",
    "wegener's granulomatosis"
  ],
  "physiotherapist": [
    "arthritis",
    "back pain",
    "carpal tunnel syndrome",
    "chronic pain syndrome",
    "concussion",
    "dizziness, vertigo, and imbalance",
    "frozen shoulder",
    "heel and foot pain",
    "low back pain",
    "motor vehicle accident injuries",
    "neck pain",
    "pelvic floor conditions",
    "post surgery",
    "repetitive strain",
    "rotator cuff injury",
    "running injuries",
    "sciatica",
    "shoulder pain",
    "sports injuries",
    "sprains and strains",
    "tendonitis",
    "tennis elbow",
    "tmj dysfunction",
    "whiplash",
    "golfer’s elbow",
    "headaches",
    "musculoskeletal problems",
    "chronic pain",
    "herniated disc",
    "migraine headaches",
    "sports injury",
    "fibromyalgia",
    "chronic fatigue",
    "car accident injuries",
    "back ache",
    "arthritis management",
    "childhood joints deformity",
    "fracture",
    "knee pain",
    "lower back pain",
    "musculoskeletal infection",
    "road traffic accident"
  ],
  "orthopedic surgeon": [
    "arthritis management",
    "back ache",
    "bone fracture",
    "bone trauma",
    "childhood joints deformity",
    "fracture",
    "knee pain",
    "ligament tear",
    "lower back pain",
    "musculoskeletal infection",
    "oesteoprosis",
    "paget's disease",
    "road traffic accident",
    "scoliosis",
    "sports injury",
    "trauma pain",
    "back pain",
    "anemia",
    "chronic fatigue",
    "fibromyalgia",
    "musculoskeletal problems",
    "sciatica",
    "car accident injuries",
    "chronic pain",
    "herniated disc",
    "neck pain",
    "arthritis",
    "post-operative pain",
    "carpal tunnel syndrome",
    "frozen shoulder",
    "golfer’s elbow",
    "heel and foot pain",
    "low back pain",
    "motor vehicle accident injuries",
    "post surgery",
    "repetitive strain",
    "rotator cuff injury",
    "running injuries",
    "shoulder pain",
    "sports injuries",
    "sprains and strains",
    "tendonitis",
    "tennis elbow",
    "tmj dysfunction",
    "osteoporosis"
  ],
  "dermatologist": [
    "acne",
    "acne scars",
    "benign and malignant skin tumors",
    "eczema",
    "herpes",
    "moles",
    "psoriasis",
    "scabies",
    "skin diseases",
    "skin fungal infections",
    "syphilis",
    "vitiligo",
    "warts",
    "angina",
    "arrythmias",
    "congenital diseases",
    "addison's disease",
    "cholesterol disorders",
    "diabetes insipidus",
    "allergic rhinitis",
    "abdominal pain",
    "acid peptic disease",
    "chronic hepatitis",
    "abdomen pain",
    "abscess",
    "anemia",
    "arthritis",
    "aids",
    "amyloidosis",
    "bronchiectasis",
    "coma",
    "coughing",
    "cystic fibrosis",
    "dengue",
    "dermatomyositis",
    "arthritis management",
    "bone fracture",
    "acute respiratory distress syndrome",
    "bronchial asthma",
    "chronic bronchitis",
    "chronic obstructive pulmonary diseases (copd)",
    "ankylosing spondylitis",
    "atopic dermatitis (eczema)",
    "skin allergy",
    "itching",
    "ingrown toe nail",
    "skin rashes"
  ],
  "consultant physician": [
    "constipation"
  ],
  "laparoscopic surgeon": [
    "anal fissure",
    "cyst",
    "fissure",
    "lumps and bumps",
    "pilonidal cysts",
    "pilonidal sinus",
    "anal and perianal conditions",
    "diabetic foot",
    "piles",
    "varicose veins",
    "sinusitis",
    "hypertension",
    "cold and influenza",
    "nausea",
    "abdomen pain",
    "abscess",
    "anemia",
    "arthritis",
    "bruise",
    "cardiac diseases",
    "chest infections",
    "chicken pox",
    "common cold",
    "fatigue",
    "fever",
    "general urology",
    "infectious diseases",
    "muscle aches",
    "respiratory diseases",
    "sleep disorders",
    "urine problems",
    "vomiting",
    "burns",
    "head injury",
    "thoracic outlet syndrome",
    "blood pressure",
    "ingrown toe nail"
  ],
  "psychologist": [
    "anxiety disorder",
    "bruxism",
    "concentration problems",
    "depression",
    "early parenting issues",
    "emotional outbursts",
    "family problems",
    "hypertension",
    "marital conflict",
    "panic disorder",
    "phobias",
    "sleep disorder",
    "social phobia",
    "stammering",
    "back pain",
    "sciatica",
    "neck pain",
    "arthritis",
    "chronic pain syndrome",
    "concussion",
    "dizziness, vertigo, and imbalance",
    "frozen shoulder",
    "heel and foot pain",
    "low back pain",
    "motor vehicle accident injuries",
    "post surgery",
    "rotator cuff injury",
    "running injuries",
    "shoulder pain",
    "sports injuries",
    "pain",
    "anxiety"
  ],
  "nutritionist": [
    "diabetes mellitus",
    "eating disorders",
    "obesity"
  ],
  "cardiologist": [
    "angina",
    "arrythmias",
    "atherosclerosis",
    "atrial fibrillation",
    "cardiac arrest",
    "cardiology diseases",
    "cardiovascular diseases",
    "congenital diseases",
    "heart attack",
    "heart diseases",
    "heart failure",
    "hypertension",
    "ischemic heart disease",
    "myocardial infarction (mi)",
    "palpitations",
    "pulmonary edema",
    "rheumatic heart disease",
    "tachycardia",
    "blood pressure",
    "high blood pressure"
  ],
  "eye specialist": [
    "blepharitis",
    "chalazion",
    "conjunctivitis",
    "diabetic retinopathy",
    "diplopia",
    "dry eye",
    "eye allergy",
    "glaucoma",
    "macular hole",
    "ocular trauma",
    "red eye",
    "retinal detachment",
    "squint",
    "strabismus",
    "stye"
  ],
  "cosmetologist": [
    "moles",
    "acne",
    "acne scars",
    "benign and malignant skin tumors",
    "eczema",
    "herpes",
    "psoriasis",
    "scabies",
    "skin fungal infections",
    "warts",
    "facial disfigurement",
    "benign skin tumors",
    "malignant skin tumors",
    "vitiligo",
    "syphilis",
    "skin allergy",
    "skin diseases"
  ],
  "dietitian": [
    "diabetes mellitus",
    "eating disorders",
    "obesity"
  ],
  "gastroenterologist": [
    "abdominal pain",
    "acid peptic disease",
    "black stools",
    "bloating",
    "chronic hepatitis",
    "diarrhea",
    "dyspepsia",
    "enteric fever",
    "flatulence",
    "fissures",
    "gas",
    "gastric ulcer",
    "gastroenteritis",
    "gerd (gastroesophageal reflux disease)",
    "heart burn",
    "helicobacter pylori bacteria",
    "hemorrhoids",
    "hepatitis b",
    "hepatitis c",
    "hernia",
    "jaundice",
    "liver diseases",
    "metabolic syndrome",
    "nausea",
    "pancreas disease",
    "typhoid fever",
    "angina",
    "arrythmias",
    "atherosclerosis",
    "atrial fibrillation",
    "cardiology diseases",
    "cardiovascular diseases",
    "congenital diseases",
    "heart attack",
    "heart diseases",
    "heart failure",
    "hypertension",
    "ischemic heart disease",
    "cold and influenza",
    "abdomen pain",
    "anemia",
    "arthritis",
    "cardiac diseases",
    "chest infections",
    "chicken pox",
    "common cold",
    "fatigue",
    "fever",
    "infectious diseases",
    "muscle aches",
    "sleep disorders",
    "stomach pain",
    "vomiting",
    "constipation",
    "indigestion",
    "diahrrea",
    "abscess",
    "diabetes mellitus"
  ],
  "radiologist": [
    "atherosclerosis",
    "brain aneurysm",
    "cancer - bone",
    "cancer - breast",
    "cancer - kidney (renal)",
    "cancer - liver",
    "cancer - lung",
    "deep venous thrombosis",
    "neurovascular malformation",
    "peripheral artery disease",
    "stroke",
    "vertebral fracture"
  ],
  "diabetologist": [
    "angina",
    "arrythmias",
    "atrial fibrillation",
    "cardiology diseases",
    "cardiovascular diseases",
    "heart diseases",
    "heart failure",
    "hypertension",
    "ischemic heart disease",
    "myocardial infarction (mi)",
    "palpitations",
    "pulmonary edema",
    "tachycardia",
    "diabetes mellitus",
    "addison's disease",
    "cancers of the endocrine gland",
    "cholesterol disorders",
    "cushing's syndrome",
    "diabetes insipidus",
    "goiter",
    "hyperthyroidism",
    "hypoglycemia",
    "hypothyroidism",
    "infertility",
    "lack of growth",
    "metabolic disorder",
    "over or under production of hormones",
    "thyroid disease",
    "turner syndrome",
    "chronic hepatitis",
    "abdomen pain",
    "dyspepsia",
    "gastric ulcer",
    "gastroenteritis",
    "hepatitis b",
    "hepatitis c",
    "liver diseases",
    "typhoid fever",
    "anemia",
    "chest infections",
    "common cold",
    "fatigue",
    "fever",
    "arthritis",
    "muscle aches",
    "oesteoprosis",
    "heart attack",
    "diarrhea",
    "gas",
    "blood pressure",
    "cough"
  ],
  "eye surgeon": [
    "blepharitis",
    "chalazion",
    "conjunctivitis",
    "diabetic retinopathy",
    "diplopia",
    "dry eye",
    "eye allergy",
    "glaucoma",
    "macular hole",
    "ocular trauma",
    "red eye",
    "retinal detachment",
    "squint",
    "strabismus",
    "stye"
  ],
  "urologist": [
    "male urinary incontinence",
    "peyronie's disease",
    "prostate disease",
    "male infertility",
    "haematuria",
    "urinary stones",
    "low testosterone",
    "premature ejaculation",
    "female urinary incontinence",
    "bedwetting",
    "bladder diverticula",
    "bladder propase",
    "blood in urine",
    "bph",
    "burning micturition",
    "enuresis",
    "epidiasis",
    "gynaecomastia",
    "hematuria",
    "hypospadias",
    "kidney infection",
    "kidney stone",
    "kidney tumor",
    "penile venous leakage",
    "perineal pain",
    "prostate cancer",
    "prostate enlargement",
    "prostratitis",
    "testicular torsion",
    "tumors of the testes",
    "ureter stones",
    "urethral stricture",
    "urinary bladder cancer",
    "urinary bladder stone",
    "urinary incontinence",
    "urinary problems",
    "urinary tract infection",
    "urine blockage",
    "varicocele",
    "abdomen pain",
    "abscess",
    "anal and perianal conditions",
    "anal fissure",
    "cyst",
    "fissure",
    "lumps and bumps",
    "pediatric hernia",
    "undescended testicles",
    "abdomen diseases in children",
    "male sexual dysfunction",
    "female urinary problems"
  ],
  "ent specialist": [
    "adenoids problem (children)",
    "allergic rhinitis",
    "choking",
    "cold and influenza",
    "deviated nasal septum",
    "difficulty in swallowing",
    "diphtheria",
    "dust allergy",
    "dysphagia",
    "ear drum rupture",
    "ear pain",
    "hay fever",
    "head and neck infections",
    "nasal injuries",
    "nasal obstructions",
    "nasal polyps",
    "pollen allergy",
    "rhinitis",
    "sinus infection",
    "sinusitis",
    "snoring in children",
    "tonsillitis",
    "vertigo (dizziness)"
  ],
  "psychiatrist": [
    "anxiety disorder",
    "aphasia",
    "attention deficit hyperactivity disorder (adhd)",
    "bipolar disorder",
    "depression",
    "hypertension",
    "learning difficulty",
    "obsessive compulsive disorder",
    "panic disorder",
    "phobias",
    "post traumatic stress disorder (ptsd)",
    "schizophrenia",
    "sleep disorder",
    "social phobia",
    "insomnia",
    "anxiety",
    "male sexual dysfunction"
  ],
  "neurosurgeon": [
    "aneurysm",
    "back pain",
    "brain hemorrhage",
    "brain tumor",
    "cerebral abscess",
    "cerebral herniation",
    "degenerative spine diseases",
    "disc rupture",
    "epilepsy",
    "fits",
    "head trauma",
    "hydrocephalus",
    "meningitis",
    "pituitary gland tumor",
    "raised intracranial pressure",
    "sciatica",
    "seizures",
    "slip disk",
    "spina bifida",
    "spinal cord injury",
    "stroke",
    "transient ischemic attack (tia)",
    "neck pain",
    "facial pain",
    "headache",
    "memory loss",
    "migraine",
    "multiple sclerosis (ms)",
    "vertigo",
    "back ache"
  ],
  "ent surgeon": [
    "sinusitis",
    "dust allergy",
    "pollen allergy",
    "adenoids problem (children)",
    "allergic rhinitis",
    "choking",
    "cold and influenza",
    "deviated nasal septum",
    "difficulty in swallowing",
    "diphtheria",
    "dysphagia",
    "ear drum rupture",
    "ear pain",
    "hay fever",
    "head and neck infections",
    "nasal injuries",
    "nasal obstructions",
    "nasal polyps",
    "rhinitis",
    "sinus infection",
    "snoring in children",
    "tonsillitis",
    "vertigo (dizziness)"
  ],
  "anesthesiologist": [
    "pain"
  ],
  "pulmonologist": [
    "tuberculosis",
    "acute respiratory distress syndrome",
    "asthma",
    "atelectasis",
    "bronchial asthma",
    "bronchiectasis",
    "bronchitis",
    "chronic bronchitis",
    "chronic obstructive pulmonary diseases (copd)",
    "cystic fibrosis",
    "embolism",
    "emphysema",
    "hypoxia",
    "interstitial lung disease (ild)",
    "lung cancer",
    "lung lymphoma",
    "mucus plug",
    "pneumonia",
    "pulmonary hypertension",
    "sarcoidosis",
    "tuberous sclerosis",
    "cardiovascular diseases",
    "heart diseases",
    "allergic rhinitis",
    "abdominal pain",
    "chronic hepatitis",
    "arthritis",
    "blood pressure",
    "cough",
    "hepatitis"
  ],
  "plastic surgeon": [
    "moles",
    "facial disfigurement",
    "benign skin tumors",
    "malignant skin tumors",
    "acne scars",
    "benign and malignant skin tumors",
    "skin fungal infections",
    "vitiligo",
    "warts",
    "skin diseases"
  ],
  "neonatologist": [
    "tonsillitis",
    "chicken pox",
    "meningitis",
    "abdomen diseases in children",
    "allergy in children",
    "asthma in children",
    "cerebral palsy (cp)",
    "chest disease in children",
    "chest infection in children",
    "childhood cancer",
    "down syndrome",
    "eating problems in children",
    "fever in children",
    "growth problem in children",
    "hypothyrodism",
    "kawasakis disease",
    "kidney problems in children",
    "measles",
    "mumps",
    "pneumonia in children",
    "respiratory disease in children",
    "respiratory tract infection (rti)",
    "rubella",
    "scarlet fever",
    "sturge weber syndrome",
    "teething issue",
    "tuberous sclerosis",
    "whooping cough",
    "bile duct stones",
    "cirrhosis",
    "hepatobiliary disease",
    "cleft lip and palate",
    "birth defects",
    "kernicterus",
    "meconium aspiration syndrome",
    "neonatal jaundice",
    "neonatal sepsis",
    "respiratory distress syndrome",
    "hemophilias",
    "idiopathic thrombocytopenic purpura (itp)",
    "platelets disorder",
    "thalassemia",
    "hepatitis a",
    "liver diseases",
    "hodgkin's lymphoma",
    "leukemia",
    "lymphoma",
    "cholestasis",
    "childhood joints deformity",
    "pediatric hernia",
    "undescended testicles",
    "albinism"
  ],
  "nephrologist": [
    "acute kidney injury",
    "acute renal failure (arf)",
    "chronic kidney disease",
    "chronic renal failure (crf)",
    "electrolyte imbalance",
    "glomerular diseases",
    "hemolytic uremic syndrome (hus)",
    "hypertension",
    "hyponatremia",
    "kidney disease",
    "kidney failure",
    "kidney infections",
    "kidney stones",
    "nephrotic syndrome",
    "orthostatic hypotension",
    "polycystic kidney disease (pkd)",
    "pyelonephritis",
    "urinary tract infections",
    "diabetes mellitus",
    "blood pressure"
  ],
  "neurologist": [
    "als",
    "autism",
    "dementia",
    "dizziness",
    "epilepsy",
    "facial pain",
    "headache",
    "imbalance",
    "memory loss",
    "meningitis",
    "migraine",
    "movement disorders",
    "multiple sclerosis (ms)",
    "neck pain",
    "neuro psychiatric disorders",
    "neurological diseases",
    "neurological issues",
    "neuromuscular disorders",
    "parkinson's disease",
    "progressive supranuclear palsy (psp)",
    "seizures",
    "sleep disorders",
    "spinal cord issues",
    "stroke",
    "vertigo"
  ],
  "endocrinologist": [
    "addison's disease",
    "cancers of the endocrine gland",
    "cholesterol disorders",
    "cushing's syndrome",
    "diabetes insipidus",
    "diabetes mellitus",
    "goiter",
    "hypertension",
    "hyperthyroidism",
    "hypoglycemia",
    "hypothyroidism",
    "infertility",
    "lack of growth",
    "metabolic disorder",
    "over or under production of hormones",
    "thyroid disease",
    "turner syndrome"
  ],
  "sexologist": [
    "erectile dysfunction",
    "fissure",
    "hydrocele",
    "night fall",
    "premature ejaculation",
    "moles",
    "benign and malignant skin tumors",
    "herpes",
    "psoriasis",
    "scabies",
    "syphilis",
    "vitiligo",
    "angina",
    "arrythmias",
    "male sexual dysfunction",
    "peyronie's disease",
    "male infertility",
    "female urinary incontinence",
    "prostate cancer",
    "undescended testicles",
    "bedwetting",
    "blood in urine",
    "bph",
    "burning micturition",
    "hypospadias",
    "kidney stone",
    "kidney tumor",
    "tumors of the testes",
    "ureter stones",
    "urethral stricture",
    "urinary bladder cancer",
    "urinary bladder stone"
  ],
  "oncologist": [
    "basal cell carcinoma",
    "blood malignancy",
    "bone cancer",
    "brain tumor",
    "breast cancer",
    "cervical cancer",
    "gastrintestinal tumors",
    "genito urinary tumour",
    "intestinal cancer",
    "leukemia (blood cancer)",
    "liver cancer",
    "lung cancer",
    "lung carcinomas and carcinoid tumors",
    "lung lymphoma",
    "lymphomas",
    "myeloma",
    "ovarian cancer",
    "ovarian tumor",
    "pancreatic cancer",
    "prostate cancer",
    "renal (kidney) cancer",
    "skin cancer",
    "squamous cell carcinoma"
  ],
  "cosmetic dentist": [
    "canine teeth",
    "jaw joint problems",
    "toothache",
    "cavities",
    "dental caries",
    "tooth decay"
  ],
  "fertility consultant": [
    "female infertility",
    "male infertility",
    "fibroids",
    "gynaecological tumors",
    "high risk pregnancy",
    "miscarriage",
    "ovarian cyst",
    "polycystic ovary syndrome (pcos)",
    "pregnancy",
    "premature ejaculation",
    "herpes",
    "syphilis",
    "night fall"
  ],
  "hepatologist": [
    "adult cystic fibrosis",
    "bile duct cancer",
    "bile duct stones",
    "bile duct strictures",
    "biliary atresia",
    "cholestasis",
    "chronic hepatitis",
    "cirrhosis",
    "gall bladder cancer",
    "gall bladder stones",
    "hepatitis a",
    "hepatitis b",
    "hepatitis c",
    "hepatobiliary disease",
    "jaundice",
    "liver diseases",
    "pancreas diseases",
    "pancreatic cancer",
    "pancreatic cysts",
    "pancreatitis",
    "wilson's disease",
    "abdominal pain",
    "acid peptic disease",
    "black stools",
    "dyspepsia",
    "enteric fever",
    "flatulence",
    "fissures",
    "gastric ulcer",
    "gastroenteritis",
    "helicobacter pylori bacteria",
    "hemorrhoids",
    "hernia",
    "metabolic syndrome",
    "nausea",
    "pancreas disease",
    "typhoid fever",
    "hypertension",
    "addison's disease",
    "cholesterol disorders",
    "cushing's syndrome",
    "goiter",
    "hyperthyroidism",
    "hypoglycemia",
    "hypothyroidism",
    "infertility",
    "metabolic disorder",
    "over or under production of hormones",
    "thyroid disease",
    "tonsillitis",
    "allergy in children",
    "asthma in children",
    "down syndrome",
    "growth problem in children",
    "hypothyrodism",
    "rubella",
    "teething issue",
    "abdomen pain",
    "fatigue",
    "fever",
    "anemia",
    "infectious diseases",
    "arthritis",
    "constipation",
    "indigestion",
    "heart burn",
    "bloating",
    "gas",
    "gerd (gastroesophageal reflux disease)",
    "stomach pain",
    "vomiting",
    "diahrrea",
    "diarrhea"
  ],
  "speech and language pathologist": [
    "depression",
    "hypertension",
    "anxiety disorder",
    "sleep disorder",
    "concentration problems",
    "early parenting issues",
    "family problems",
    "marital conflict",
    "stammering",
    "sports injuries",
    "phobias",
    "social phobia"
  ],
  "laser specialist": [
    "moles",
    "acne",
    "acne scars",
    "skin fungal infections",
    "benign and malignant skin tumors",
    "eczema",
    "herpes",
    "psoriasis",
    "scabies",
    "syphilis",
    "vitiligo",
    "warts",
    "facial disfigurement",
    "benign skin tumors",
    "canine teeth",
    "jaw joint problems",
    "orofacial pain",
    "periodontitis",
    "tmj disorders",
    "sinusitis",
    "hypertension",
    "sports injury",
    "goiter",
    "hyperthyroidism",
    "hypoglycemia",
    "hypothyroidism",
    "thyroid disease",
    "cold and influenza",
    "acid peptic disease",
    "flatulence",
    "fissures",
    "gastric ulcer",
    "gastroenteritis",
    "jaundice",
    "nausea",
    "typhoid fever",
    "abdomen pain",
    "abscess",
    "anemia",
    "arthritis",
    "bruise",
    "cardiac diseases",
    "chest infections",
    "chicken pox",
    "common cold",
    "fatigue",
    "fever",
    "infectious diseases",
    "muscle aches",
    "respiratory diseases",
    "urine problems",
    "vomiting",
    "dengue",
    "arthritis management",
    "knee pain",
    "lower back pain",
    "musculoskeletal infection",
    "oesteoprosis",
    "trauma pain",
    "skin allergy"
  ],
  "oral and maxillofacial surgeon": [
    "canine teeth",
    "dental caries",
    "orofacial pain",
    "periodontitis",
    "tmj disorders",
    "cavities",
    "dupuytren's contracture (hypodontia)",
    "gingivitis",
    "gum disease (periodontal)",
    "jaw joint problems",
    "tooth decay",
    "toothache"
  ],
  "orthodontist": [
    "canine teeth",
    "cavities",
    "dental caries",
    "gum disease (periodontal)",
    "jaw joint problems",
    "tooth decay",
    "toothache",
    "orofacial pain",
    "dupuytren's contracture (hypodontia)",
    "gingivitis",
    "periodontitis",
    "tmj disorders"
  ],
  "pain management specialist": [
    "chronic pain",
    "post-operative pain",
    "sports injury",
    "back ache",
    "arthritis management",
    "childhood joints deformity",
    "fracture",
    "knee pain",
    "ligament tear",
    "lower back pain",
    "musculoskeletal infection",
    "road traffic accident",
    "scoliosis",
    "back pain",
    "chronic fatigue",
    "dizziness",
    "fibromyalgia",
    "headaches",
    "musculoskeletal problems",
    "sciatica",
    "car accident injuries",
    "herniated disc",
    "migraine headaches",
    "neck pain"
  ],
  "pediatric surgeon": [
    "chest deformity",
    "cleft lip and palate",
    "conjoined twins",
    "pediatric hernia",
    "retinopathy of prematurity",
    "undescended testicles"
  ],
  "male sexual health specialist": [
    "erectile dysfunction",
    "male urinary incontinence",
    "male infertility",
    "low testosterone",
    "premature ejaculation",
    "herpes",
    "scabies",
    "syphilis",
    "abdomen pain",
    "abscess",
    "anal and perianal conditions",
    "anal fissure",
    "fissure",
    "female infertility",
    "polycystic ovary syndrome (pcos)",
    "night fall",
    "bedwetting",
    "blood in urine",
    "bph",
    "burning micturition",
    "enuresis",
    "kidney stone",
    "prostate enlargement",
    "prostratitis",
    "urinary incontinence",
    "urinary tract infection",
    "peyronie's disease",
    "haematuria",
    "kidney infection",
    "urinary problems",
    "male sexual dysfunction",
    "prostate disease",
    "urinary stones",
    "female urinary incontinence",
    "cyst",
    "prostate cancer",
    "pediatric hernia",
    "undescended testicles",
    "bladder diverticula",
    "epidiasis",
    "hematuria",
    "hypospadias",
    "kidney tumor",
    "penile venous leakage",
    "perineal pain",
    "testicular torsion",
    "tumors of the testes",
    "ureter stones",
    "urethral stricture",
    "urinary bladder cancer",
    "urinary bladder stone",
    "urine blockage",
    "varicocele"
  ],
  "spinal surgeon": [
    "back pain",
    "brain tumor"
  ],
  "implantologist": [
    "cavities",
    "dental caries",
    "gum disease (periodontal)",
    "periodontitis",
    "tooth decay",
    "toothache",
    "canine teeth",
    "dupuytren's contracture (hypodontia)",
    "gingivitis",
    "jaw joint problems",
    "orofacial pain",
    "tmj disorders"
  ],
  "hypertension specialist": [
    "congenital diseases",
    "cholesterol disorders",
    "diabetes insipidus",
    "thyroid disease",
    "cold and influenza",
    "abdominal pain",
    "acid peptic disease",
    "black stools",
    "chronic hepatitis",
    "dyspepsia",
    "enteric fever",
    "gastric ulcer",
    "gastroenteritis",
    "typhoid fever",
    "abdomen pain",
    "anemia",
    "blood pressure",
    "cardiac diseases",
    "chicken pox",
    "common cold",
    "fatigue",
    "fever",
    "sleep disorders",
    "high blood pressure"
  ],
  "sonologist": [
    "infectious diseases",
    "amenorrhoea",
    "aplastic anemia",
    "female infertility",
    "fibroids",
    "menstruation problems",
    "ovarian cyst",
    "uro gynae cancer",
    "hypertension",
    "infertility",
    "nausea",
    "typhoid fever",
    "abdomen pain",
    "anemia",
    "common cold",
    "fatigue",
    "fever",
    "muscle aches",
    "urine problems",
    "vomiting",
    "endometriosis",
    "gynaecological tumors",
    "post menopausal bleeding",
    "preeclampsia",
    "urinary tract infections (uti)",
    "lower back pain"
  ],
  "hematologist": [
    "hemophilias",
    "hodgkin's lymphoma",
    "idiopathic thrombocytopenic purpura (itp)",
    "leukemia",
    "lymphoma",
    "platelets disorder",
    "thalassemia",
    "toxoplasmosis",
    "ttp"
  ],
  "cosmetic surgeon": [
    "moles",
    "facial disfigurement",
    "benign skin tumors",
    "malignant skin tumors",
    "benign and malignant skin tumors",
    "skin diseases",
    "warts",
    "acne scars"
  ],
  "andrologist": [
    "erectile dysfunction",
    "female urinary incontinence",
    "haematuria",
    "low testosterone",
    "male infertility",
    "male urinary incontinence",
    "peyronie's disease",
    "premature ejaculation",
    "prostate disease",
    "urinary stones"
  ],
  "cardiac surgeon": [
    "angina",
    "atherosclerosis",
    "atrial fibrillation",
    "cardiac arrest",
    "cardiology diseases",
    "cardiovascular diseases",
    "congenital diseases",
    "heart attack",
    "heart diseases",
    "heart failure",
    "hypertension",
    "ischemic heart disease",
    "myocardial infarction (mi)",
    "palpitations",
    "pulmonary edema",
    "tachycardia"
  ],
  "interventional cardiologist": [
    "angina",
    "arrythmias",
    "atherosclerosis",
    "atrial fibrillation",
    "cardiac arrest",
    "cardiology diseases",
    "cardiovascular diseases",
    "congenital diseases",
    "heart attack",
    "heart diseases",
    "heart failure",
    "hypertension",
    "ischemic heart disease",
    "myocardial infarction (mi)",
    "palpitations",
    "pulmonary edema",
    "rheumatic heart disease",
    "tachycardia",
    "cholesterol disorders",
    "diabetes insipidus",
    "goiter",
    "hyperthyroidism",
    "hypoglycemia",
    "hypothyroidism",
    "lack of growth",
    "thyroid disease",
    "cold and influenza",
    "abdominal pain",
    "acid peptic disease",
    "black stools",
    "chronic hepatitis",
    "dyspepsia",
    "enteric fever",
    "flatulence",
    "fissures",
    "gastric ulcer",
    "gastroenteritis",
    "helicobacter pylori bacteria",
    "hemorrhoids",
    "hepatitis b",
    "hepatitis c",
    "hernia",
    "jaundice",
    "liver diseases",
    "metabolic syndrome",
    "nausea",
    "pancreas disease",
    "typhoid fever",
    "abdomen pain",
    "anemia",
    "arthritis",
    "blood pressure",
    "cardiac diseases",
    "chest infections",
    "common cold",
    "fatigue",
    "fever",
    "infectious diseases",
    "muscle aches",
    "respiratory diseases",
    "sleep disorders",
    "bronchiectasis",
    "pulmonary hypertension",
    "tuberculosis",
    "bronchial asthma",
    "chronic bronchitis",
    "chronic obstructive pulmonary diseases (copd)",
    "embolism",
    "emphysema",
    "interstitial lung disease (ild)"
  ],
  "rheumatologist": [
    "ankylosing spondylitis",
    "behcet's disease",
    "bursitis / tendinitis",
    "churg-strauss dyndrome",
    "corticosteroid-induced osteoporosis",
    "fibromyalgia",
    "giant cell arteritis",
    "gout",
    "henoch-schonlein purpura",
    "hypersensitivity vasculitis",
    "juvenile rheumatoid arthritis",
    "kawasaki syndrome",
    "lupus",
    "lupus nephritis",
    "lyme disease",
    "mixed connective tissue disease",
    "myositis",
    "osteoarthritis",
    "polyarteritis nodosa",
    "polymyalgia rheumatica",
    "polymyositis / dermatomyositis",
    "primary antiphospholipid syndrome",
    "psoriatic arthritis",
    "raynaud's phenomenon",
    "reactive arthritis",
    "rheumatoid arthritis",
    "scleroderma",
    "sjögren's syndrome",
    "takayasu's arteritis",
    "undifferentiated spondyloarthropathy",
    "vasculitis",
    "wegener's granulomatosis",
    "cardiovascular diseases",
    "heart failure",
    "hypertension",
    "ischemic heart disease",
    "acid peptic disease",
    "chronic hepatitis",
    "helicobacter pylori bacteria",
    "hepatitis b",
    "hepatitis c",
    "liver diseases",
    "metabolic syndrome",
    "typhoid fever",
    "anemia",
    "chest infections",
    "respiratory diseases",
    "tuberculosis",
    "chronic bronchitis",
    "chronic obstructive pulmonary diseases (copd)",
    "interstitial lung disease (ild)",
    "angina",
    "arrythmias",
    "hyperthyroidism",
    "hypoglycemia",
    "hypothyroidism",
    "thyroid disease",
    "cold and influenza",
    "abdominal pain",
    "black stools",
    "dyspepsia",
    "enteric fever",
    "flatulence",
    "gastric ulcer",
    "gastroenteritis",
    "jaundice",
    "nausea",
    "pancreas disease",
    "arthritis",
    "cardiac diseases",
    "common cold",
    "fatigue",
    "fever",
    "infectious diseases",
    "osteoporosis"
  ],
  "homeopath": [
    "abdomen pain",
    "anemia",
    "arthritis",
    "burns",
    "cardiac diseases",
    "chest infections",
    "chicken pox",
    "cold and influenza",
    "common cold",
    "cyst",
    "fatigue",
    "fever",
    "hypertension",
    "muscle aches",
    "nausea",
    "piles",
    "sleep disorders",
    "urine problems",
    "varicose veins",
    "vomiting"
  ],
  "chiropractor": [
    "back pain",
    "chronic fatigue",
    "dizziness",
    "fibromyalgia",
    "headaches",
    "musculoskeletal problems",
    "sciatica",
    "car accident injuries",
    "chronic pain",
    "herniated disc",
    "hiatal hernia",
    "migraine headaches",
    "neck pain",
    "sports injury"
  ],
  "endodontist": [
    "canine teeth",
    "cavities",
    "dental caries",
    "dupuytren's contracture (hypodontia)",
    "gingivitis",
    "gum disease (periodontal)",
    "jaw joint problems",
    "orofacial pain",
    "periodontitis",
    "tmj disorders",
    "tooth decay",
    "toothache",
    "emotional outbursts"
  ],
  "acupuncturist": [
    "allergies",
    "back pain",
    "chronic fatigue",
    "depression",
    "dizziness",
    "fibromyalgia",
    "headaches",
    "musculoskeletal problems",
    "sciatica",
    "sexual dysfunction",
    "sinusitis",
    "tmj"
  ],
  "rehabilitation specialist": [
    "back pain",
    "chronic fatigue",
    "fibromyalgia",
    "musculoskeletal problems",
    "sciatica",
    "tmj",
    "headaches",
    "chronic pain",
    "migraine headaches",
    "neck pain",
    "sports injury",
    "arthritis",
    "carpal tunnel syndrome",
    "chronic pain syndrome",
    "dizziness, vertigo, and imbalance",
    "frozen shoulder",
    "golfer’s elbow",
    "heel and foot pain",
    "low back pain",
    "motor vehicle accident injuries",
    "pelvic floor conditions",
    "post surgery",
    "repetitive strain",
    "rotator cuff injury",
    "running injuries",
    "shoulder pain",
    "sports injuries",
    "sprains and strains",
    "tendonitis",
    "tennis elbow",
    "tmj dysfunction",
    "whiplash",
    "dizziness",
    "car accident injuries",
    "herniated disc",
    "depression",
    "male infertility",
    "congenital diseases",
    "hypertension",
    "lung cancer",
    "moles",
    "facial disfigurement",
    "benign skin tumors",
    "malignant skin tumors",
    "benign and malignant skin tumors",
    "herpes",
    "psoriasis",
    "scabies",
    "skin fungal infections",
    "syphilis",
    "vitiligo",
    "eating disorders",
    "obesity",
    "cholesterol disorders",
    "diabetes insipidus",
    "thyroid disease",
    "cold and influenza",
    "tonsillitis",
    "abdominal pain",
    "acid peptic disease",
    "black stools",
    "chronic hepatitis",
    "dyspepsia",
    "enteric fever",
    "gastric ulcer",
    "gastroenteritis",
    "nausea",
    "typhoid fever",
    "abdomen pain",
    "anemia",
    "cardiac diseases",
    "chest infections",
    "chicken pox",
    "common cold",
    "fatigue",
    "fever",
    "infectious diseases",
    "muscle aches",
    "sleep disorders",
    "urine problems",
    "vomiting",
    "burns",
    "cyst",
    "varicose veins",
    "amenorrhoea",
    "aplastic anemia",
    "endometriosis",
    "female infertility",
    "fibroids",
    "gynaecological tumors",
    "menstruation problems",
    "ovarian cyst",
    "post menopausal bleeding",
    "preeclampsia",
    "urinary tract infections (uti)",
    "bile duct stones",
    "hepatitis a",
    "bronchiectasis",
    "pulmonary hypertension",
    "tuberculosis",
    "acute kidney injury",
    "chronic kidney disease",
    "glomerular diseases",
    "kidney disease",
    "pyelonephritis",
    "urinary tract infections",
    "meningitis",
    "arthritis management",
    "childhood joints deformity",
    "fracture",
    "knee pain",
    "ligament tear",
    "lower back pain",
    "musculoskeletal infection",
    "road traffic accident",
    "scoliosis",
    "abdomen diseases in children",
    "allergy in children",
    "asthma in children",
    "chest disease in children",
    "down syndrome",
    "growth problem in children",
    "kidney problems in children",
    "measles",
    "mumps",
    "pneumonia in children",
    "respiratory disease in children",
    "scarlet fever",
    "concussion",
    "anxiety disorder",
    "panic disorder",
    "sleep disorder",
    "bruxism",
    "concentration problems",
    "early parenting issues",
    "emotional outbursts",
    "family problems",
    "marital conflict",
    "stammering",
    "acute respiratory distress syndrome",
    "bronchial asthma",
    "chronic bronchitis",
    "hypoxia",
    "mucus plug",
    "sarcoidosis",
    "night fall"
  ],
  "pediatric orthopedic surgeon": [
    "bone fracture",
    "childhood joints deformity",
    "ligament tear",
    "road traffic accident",
    "trauma pain"
  ],
  "sports medicine specialist": [
    "back pain",
    "sciatica",
    "car accident injuries",
    "chronic pain",
    "herniated disc",
    "neck pain",
    "sports injury",
    "carpal tunnel syndrome",
    "golfer’s elbow",
    "heel and foot pain",
    "low back pain",
    "sprains and strains",
    "tendonitis",
    "tmj dysfunction",
    "arthritis",
    "chronic pain syndrome",
    "concussion",
    "dizziness, vertigo, and imbalance",
    "frozen shoulder",
    "motor vehicle accident injuries",
    "pelvic floor conditions",
    "post surgery",
    "repetitive strain",
    "rotator cuff injury",
    "running injuries",
    "shoulder pain",
    "sports injuries",
    "tennis elbow",
    "whiplash"
  ],
  "pediatric nutritionist": [
    "diabetes mellitus",
    "eating disorders",
    "obesity"
  ],
  "thyroid surgeon": [
    "anal and perianal conditions",
    "anal fissure",
    "burns",
    "cyst",
    "diabetic foot",
    "fissure",
    "lumps and bumps",
    "pilonidal cysts",
    "pilonidal sinus",
    "varicose veins",
    "abdomen pain",
    "abscess",
    "bruise",
    "urine problems",
    "piles"
  ],
  "restorative dentist": [
    "canine teeth",
    "cavities",
    "dental caries",
    "gingivitis",
    "gum disease (periodontal)",
    "periodontitis",
    "tooth decay",
    "toothache",
    "dupuytren's contracture (hypodontia)",
    "jaw joint problems",
    "orofacial pain",
    "tmj disorders"
  ],
  "prosthodontist": [
    "canine teeth",
    "cavities",
    "dental caries",
    "dupuytren's contracture (hypodontia)",
    "gingivitis",
    "gum disease (periodontal)",
    "jaw joint problems",
    "orofacial pain",
    "periodontitis",
    "tmj disorders",
    "tooth decay",
    "toothache"
  ],
  "vascular surgeon": [
    "abdominal aortic aneurysm (aaa)",
    "aortic arch conditions",
    "aortoiliac occlusive disease",
    "arm artery disease",
    "carotid artery disease",
    "chronic pelvic pain",
    "chronic ulcers of the leg/foot",
    "chronic venous insufficiency",
    "chronic venous thrombosis",
    "deep vein thrombosis (dvt)",
    "diabetic vascular disease",
    "digital artery conditions",
    "hyperlipidemia",
    "hypertension",
    "leg artery disease",
    "liver disease",
    "lymphedema",
    "pelvic venous incompetence",
    "peripheral artery disease (pad)",
    "portal hypertension",
    "pulmonary embolism",
    "renal failure",
    "renovascular conditions",
    "stroke",
    "thoracic aneurysm",
    "thoracic outlet syndrome",
    "varicose and spider veins",
    "vascular malformations",
    "venous ulcerations",
    "visceral artery conditions"
  ],
  "audiologist": [
    "balance disorder",
    "benign paroxysmal positional vertigo (bppv)",
    "dizziness",
    "hearing loss"
  ],
  "head and neck surgeon": [
    "sinusitis",
    "dust allergy",
    "pollen allergy",
    "adenoids problem (children)",
    "allergic rhinitis",
    "cold and influenza",
    "deviated nasal septum",
    "difficulty in swallowing",
    "diphtheria",
    "dysphagia",
    "ear drum rupture",
    "ear pain",
    "head and neck infections",
    "nasal injuries",
    "nasal obstructions",
    "nasal polyps",
    "rhinitis",
    "sinus infection",
    "snoring in children",
    "tonsillitis",
    "vertigo (dizziness)",
    "choking",
    "hay fever"
  ],
  "burns specialist": [
    "moles",
    "facial disfigurement",
    "benign skin tumors",
    "malignant skin tumors",
    "acne scars",
    "warts"
  ],
  "sleep medicine doctor": [
    "lung cancer",
    "bronchiectasis",
    "pulmonary hypertension",
    "tuberculosis",
    "acute respiratory distress syndrome",
    "atelectasis",
    "bronchial asthma",
    "chronic bronchitis",
    "chronic obstructive pulmonary diseases (copd)",
    "embolism",
    "emphysema",
    "hypoxia",
    "interstitial lung disease (ild)",
    "mucus plug",
    "sarcoidosis"
  ],
  "cardiothoracic surgeon": [
    "aorta transaction",
    "aortic dissection (bleeding in the aorta walls)",
    "atrial fibrillation",
    "congestive heart failure (ineffective heart muscle)",
    "coronary artery disease (artery blockage)",
    "esophageal cancer and benign conditions of the esophagus",
    "left ventricular aneurysm (stretched heart muscle)",
    "lung cancer",
    "mediastinal tumors",
    "myocardial infarction (heart attack)",
    "thoracic aortic aneurysm (stretched aorta in chest)",
    "thoracoabdominal aortic aneurysm",
    "tracheal stenosis",
    "tracheobronchial cancer",
    "valvular insufficiency (leaking or regurgitation)",
    "valvular stenosis (blocked or narrowed valves)"
  ],
  "pediatric cardiologist": [
    "angina",
    "arrythmias",
    "atherosclerosis",
    "atrial fibrillation",
    "cardiac arrest",
    "cardiology diseases",
    "cardiovascular diseases",
    "congenital diseases",
    "heart diseases",
    "heart failure",
    "hypertension",
    "ischemic heart disease",
    "myocardial infarction (mi)",
    "palpitations",
    "pulmonary edema",
    "rheumatic heart disease",
    "tachycardia",
    "congenital heart diseases",
    "tetralogy of fallot",
    "ventricular septal defect (vsd)"
  ],
  "diabetes counsellor": [
    "heart diseases",
    "hypertension",
    "diabetes mellitus",
    "addison's disease",
    "cholesterol disorders",
    "diabetes insipidus",
    "hyperthyroidism",
    "hypoglycemia",
    "hypothyroidism",
    "lack of growth",
    "metabolic disorder",
    "thyroid disease"
  ],
  "aesthetic gynecologist": [
    "angina",
    "atherosclerosis"
  ],
  "child-kidney specialist": [
    "abdomen diseases in children",
    "cerebral palsy (cp)",
    "bile duct stones",
    "kidney problems in children",
    "hypertension",
    "tonsillitis",
    "chicken pox",
    "hepatitis a",
    "acute kidney injury",
    "chronic kidney disease",
    "glomerular diseases",
    "hemolytic uremic syndrome (hus)",
    "kidney disease",
    "pyelonephritis",
    "urinary tract infections",
    "meningitis",
    "childhood joints deformity",
    "allergy in children",
    "asthma in children",
    "chest disease in children",
    "down syndrome",
    "growth problem in children",
    "measles",
    "mumps",
    "pneumonia in children",
    "respiratory disease in children",
    "scarlet fever"
  ],
  "immunologist": [
    "acute hives",
    "allergic conjunctivitis",
    "allergic middle ear dysfunction",
    "allergic nasal polyposis",
    "allergic rhinitis (hay fever)",
    "allergic rhinosinusitis",
    "allergy to medication",
    "anaphylaxis",
    "angioedema",
    "chronic cough",
    "churg strauss syndrome",
    "contact dermatitis",
    "dress - drug rash eosinophilia systemic syndrome",
    "drug allergy",
    "dust allergy",
    "eosinophilic esophagitis",
    "eosinophilic gastroenteritis",
    "exercise-induced bronchospasm",
    "food allergy",
    "food protein enterocolitis (fpies)",
    "food protein proctocolitis",
    "hiener's syndrome",
    "histamine toxicity",
    "hives",
    "hypersensitive pneumonitis (hp)",
    "immunodeficiency disorders",
    "insect venom allergy",
    "lactose intolerance",
    "latex allergy",
    "nose / sinus allergy",
    "penicillin allergy",
    "pollen allergy",
    "reactive airway disease",
    "respiratory allergy",
    "skeeter syndrome",
    "steven johnson syndrome",
    "systemic mastocytosis",
    "toxic epidermal necrolysis",
    "vaccine allergy",
    "vocal cord dysfunction"
  ]
}

export default conditions;
