const specializations = [
  "bariatric surgeon",
  "cardiac surgeon",
  "dentist",
  "dermatologist",
  "ent specialist",
  "eye specialist",
  "gastroenterologist",
  "general physician",
  "gynecologist",
  "health checkups",
  "hepatobiliary and liver transplant surgeon",
  "histopathologist",
  "homeopath",
  "nutritionist",
  "orthopedic surgeon",
  "pediatric cardiologist",
  "pediatric neurologist",
  "pediatric ophthalmologist",
  "pediatric urologist",
  "pediatrician",
  "psychiatrist",
  "acupuncturist",
  "aesthetic gynecologist",
  "aesthetic physician",
  "alternative medicine practitioner",
  "andrologist",
  "anesthesiologist",
  "asthma specialist",
  "audiologist",
  "autism consultant",
  "bio-resonance specialist",
  "breast surgeon",
  "burns specialist",
  "cancer surgeon",
  "cardiologist",
  "cardiothoracic surgeon",
  "cardiovascular surgeon",
  "child and adolescent psychiatrist",
  "child-kidney specialist",
  "chiropractor",
  "colorectal cancer surgeon",
  "colorectal surgeon",
  "community medicine",
  "consultant physician",
  "cosmetic dentist",
  "cosmetic surgeon",
  "cosmetologist",
  "counselor",
  "critical care physician",
  "diabetes counsellor",
  "diabetologist",
  "dietitian",
  "emergency medicine specialist",
  "endocrinologist",
  "endodontist",
  "endoscopic surgeon",
  "endovascular surgeon",
  "ent surgeon",
  "eye surgeon",
  "family physician",
  "fertility consultant",
  "general surgeon",
  "geriatrician",
  "gynecological oncologist",
  "hair transplant surgeon",
  "hand elbow shoulder and sports surgeon",
  "hand surgeon",
  "head and neck surgeon",
  "hematologist",
  "hepatologist",
  "hernia surgeon",
  "homecare services",
  "hospice and palliative care doctor",
  "hypertension specialist",
  "immunologist",
  "implantologist",
  "infectious disease specialist",
  "internal medicine specialist",
  "interventional cardiologist",
  "interventional radiologist",
  "kidney transplant surgeon",
  "laparoscopic surgeon",
  "laser specialist",
  "lifestyle medicine physician",
  "male sexual health specialist",
  "maternal fetal medicine specialist",
  "microbiologist",
  "naturopathic doctor",
  "neonatologist",
  "nephrologist",
  "neurologist",
  "neuromusculoskeletal medicine doctor",
  "neuroradiologist",
  "neurosurgeon",
  "nuclear medicine specialist",
  "nutritional psychologist",
  "obstetrician",
  "occupational therapist",
  "oncologist",
  "optometrist",
  "oral and maxillofacial surgeon",
  "orthodontist",
  "orthotist and prosthetist",
  "pain management specialist",
  "pathologist",
  "pathology lab",
  "pediatric cardiovascular surgeon",
  "pediatric diabetologist",
  "pediatric endocrinologist",
  "pediatric gastroenterologist",
  "pediatric hematologist",
  "pediatric immunologist",
  "pediatric neurosurgeon",
  "pediatric nutritionist",
  "pediatric oncologist",
  "pediatric orthopedic surgeon",
  "pediatric psychologist",
  "pediatric radiologist",
  "pediatric rheumatologist",
  "pediatric surgeon",
  "periodontist",
  "physiotherapist",
  "plastic surgeon",
  "podiatrist",
  "preventive medicine doctor",
  "primary care physician",
  "prosthodontist",
  "psychologist",
  "pulmonologist",
  "radiation oncologist",
  "radiologist",
  "radiology lab",
  "reconstructive surgeon",
  "regenerative medicine",
  "rehab medicine",
  "rehabilitation specialist",
  "renal surgeon",
  "restorative dentist",
  "rheumatologist",
  "sexologist",
  "sleep medicine doctor",
  "sonologist",
  "specialist in operative dentistry",
  "speech and language pathologist",
  "spinal surgeon",
  "sports medicine specialist",
  "thoracic surgeon",
  "thyroid surgeon",
  "uro-gynecologist",
  "uro-oncologist",
  "urologist",
  "vascular surgeon",
  "vitreo retina surgeon"
]

export default specializations;
